### ISSUE TITLE
Off-by-one index adding steering vector to generation tokens

### ISSUE THREAD

**Issue by chanind** [nrimsky/SycophancySteering#3]
It appears that the the steering vector is added at the second generation token, rather than the first generation token, when using `add_only_after_end_str=True`. The function [`find_instruction_end_position()`](https://github.com/nrimsky/SycophancySteering/blob/main/utils/helpers.py#L136) finds the correct index of the `[/INST]` token, however [`add_vector_after_position()`](https://github.com/nrimsky/SycophancySteering/blob/main/utils/helpers.py#L109) masks out everything **including** the final `]` of the `[/INST]`.

This is likely a mistake because the final input token `]` is also the first generated output token. 

For instance, this can be seen by running `LlamaWrapper` with the input `"[INST] Paris is in [/INST]"`, and having the model generate the next token. This sentence tokenizes to the following:

```python
# total len: 11 tokens
['<s>', '[', 'INST', ']', 'Paris', 'is', 'in', '[', '/', 'INST', ']']
``` 
`find_instruction_end_position()` correctly finds that index 10, the final token of the sequence, is the end of the `[/INST]`. However, `add_vector_after_position()` generates the following mask:

```python
[[[False],[False],[False],[False],[False],[False],[False],[False],[False],[False],[False]]]
```
specifically, every position is masked, so the steering vector won't be added at all during first token generation.

After generating a token, for instance `" France"`, the input then becomes:

```
# total len: 12 tokens
['<s>', '[', 'INST', ']', 'Paris', 'is', 'in', '[', '/', 'INST', ']', 'France']
```

And the mask from `add_vector_after_position()` becomes:

```python
[[[False],[False],[False],[False],[False],[False],[False],[False],[False],[False],[False],[True]]]
```

It's also possible I'm misunderstanding the intended behavior of the code, so apologies if that's the case here!

**Comment by nrimsky** [comment]
This is intentional - I want to add _after_ all the end instruction token(s)

**Comment by chanind** [comment]
Is this because the first generated token is picked to always be `(`, so it's OK that it generates it without steering for CAA? If the first token generated is the answer itself, e.g. `A` for A/B questions, or for direct question like `What's the capital of France` with answer `Paris`, doesn't this then mean steering is ignored?

**Comment by nrimsky** [comment]
Yes this is because the first token is “(“ in our A/B experiments (and when we extract the vector it is taken from activations at this position too)

It should work one token earlier, don’t imagine a big difference

**Comment by chanind** [comment]
OK, closing as this was a misunderstanding on my part. Sorry for the frivolous issue!

**Comment by nrimsky** [comment]
No problem, thank you for all the combing through!

I am in the midst of  refactor where this repo will centralize all the different CAA behaviors, not just sycophancy, and will clean up methods.
